# Generated by Django 4.2 on 2023-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='header_image',
            field=models.ImageField(default=None, upload_to='images/destinations'),
            preserve_default=False,
        ),
    ]
