# Generated by Django 4.2 on 2023-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='details',
            field=models.TextField(),
        ),
    ]
