# Generated by Django 4.2 on 2023-04-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/destinations'),
        ),
    ]
