# Generated by Django 4.2 on 2023-05-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_destination_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['rank']},
        ),
    ]
