# Generated by Django 4.2 on 2023-04-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_alter_inquiry_no_of_days_alter_inquiry_no_of_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
    ]
