# Generated by Django 4.2 on 2023-05-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_alter_inquiry_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAdminInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField()),
                ('amount_paid', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Event Admin Inquiries',
            },
        ),
    ]
