version: '3'

services:
  nepal_env_db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: ['./wait-for-it.sh', 'nepal_env_db:5432', '--', '/code/run_develop.sh']
    volumes:
      - .:/code
      - ./uploads:/uploads
    ports:
      - '8000:8000'
    depends_on:
      - nepal_env_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env.development
