# Generated by Django 4.2 on 2023-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_amenities_price_tier_full_itinerary_daily_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amenities',
            field=models.ManyToManyField(to='packages.amenities'),
        ),
    ]
