# Generated by Django 4.2 on 2023-04-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Daily_itinerary',
            new_name='DailyItinerary',
        ),
        migrations.RenameModel(
            old_name='Full_itinerary',
            new_name='FullItinerary',
        ),
        migrations.RenameModel(
            old_name='Price_Tier',
            new_name='PriceTier',
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.AlterField(
            model_name='package',
            name='amenities',
            field=models.ManyToManyField(to='packages.amenity'),
        ),
    ]
