# Generated by Django 4.2 on 2023-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_amenity_rename_daily_itinerary_dailyitinerary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='dailyitinerary',
            options={'verbose_name_plural': 'Daily Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='fullitinerary',
            options={'verbose_name_plural': 'Full Itineraries'},
        ),
        migrations.AddField(
            model_name='activity',
            name='header_image',
            field=models.ImageField(default=None, upload_to='images/destinations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='header_image',
            field=models.ImageField(default=None, upload_to='images/destinations'),
            preserve_default=False,
        ),
    ]
