# Generated by Django 4.2 on 2023-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_activity_options_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyitinerary',
            options={'ordering': ['day'], 'verbose_name_plural': 'Daily Itineraries'},
        ),
        migrations.AddField(
            model_name='dailyitinerary',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
