# Generated by Django 4.2 on 2023-04-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_dailyitinerary_options_dailyitinerary_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyitinerary',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='price',
            field=models.FloatField(),
        ),
    ]
