# Generated by Django 4.2 on 2023-04-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_alter_dailyitinerary_duration_alter_pricetier_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/destinations'),
        ),
    ]
