# Generated by Django 4.2 on 2023-04-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_activity_details_alter_activity_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('strenous', 'Strenous')], max_length=20),
        ),
    ]
