# Generated by Django 4.2 on 2023-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_package_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyitinerary',
            name='max_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
