# Generated by Django 4.2 on 2023-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_dailyitinerary_max_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('strenous', 'Strenous')], max_length=20, null=True),
        ),
    ]
