# Generated by Django 4.2 on 2023-05-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_alter_package_difficulty_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='pricetier',
            name='package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
            preserve_default=False,
        ),
    ]
