# Generated by Django 4.2 on 2023-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_alter_package_options_pricetier_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetier',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='package',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='packages.amenity'),
        ),
    ]
