# Generated by Django 4.2 on 2023-05-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_alter_activity_options_activity_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('strenuous', 'Strenuous')], max_length=20, null=True),
        ),
    ]
