# Generated by Django 4.2 on 2023-05-19 01:44

from django.db import migrations, models
from django.utils.text import slugify


def update_slugs(apps, schema_editor):
    Package = apps.get_model('packages', 'Package')
    for package in Package.objects.all():
        package.slug = slugify(package.title)
        package.save()


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_alter_package_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True),
        ),

        migrations.RunPython(update_slugs, reverse_code=migrations.RunPython.noop)
    ]
