# Generated by Django 4.2 on 2023-05-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_specialevent_alter_package_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialevent',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='specialevent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
