# Generated by Django 4.2 on 2023-05-20 00:51

from django.db import migrations, models
from django.utils.text import slugify


def update_slugs(apps, schema_editor):
    SpecialEvent = apps.get_model('packages', 'SpecialEvent')
    for event in SpecialEvent.objects.all():
        event.slug = slugify(event.title)
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_rename_name_specialevent_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(update_slugs, reverse_code=migrations.RunPython.noop)
    ]
