# Generated by Django 4.2 on 2023-05-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_specialevent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialevent',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
