# Generated by Django 4.2 on 2023-04-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('po_box', models.CharField(max_length=255)),
            ],
        ),
    ]
