# Generated by Django 4.2 on 2023-04-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_info',
            new_name='ContactInformation',
        ),
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name_plural': 'Contact Informations'},
        ),
    ]
